Update to 1.17
YTG1234/manhunt-fabric pull request #17
Opened 2021-08-04 18:09 UTC by BeetMacol

Updates the mod to **Minecraft 1.17.1**. Also updates to Java 16, but I didn't add any Java 9+ features here.

2021-08-04 18:12 UTC, BeetMacol commented
I'm not sure, but it seems like this mirror is not updated with the GitLab repo. f0ab32f3c8c56c4c793ab34d2167e4b58cf4bf62 was pushed by @YTG1234 and is on the GitLab remote, but didn't end up here.

2021-08-04 21:46 UTC, YTG1234 commented
> I'm not sure, but it seems like this mirror is not updated with the GitLab repo. f0ab32f3c8c56c4c793ab34d2167e4b58cf4bf62 was pushed by @YTG1234 and is on the GitLab remote, but didn't end up here (and that's why this pull request also adds the YTG's commit).

That's weird. I set up the GL repo to automatically mirror.

On that note, I think I forgot to mention anywhere that this is an effectively read-only mirror, and only syncs GL->GH. I can (and probably will) merge this manually, but I would prefer that further PRs be opened on GitLab instead.

After all PRs are merged/closed, I will disable PRs in this repo.

2021-08-04 21:51 UTC, YTG1234 requested changes
The mixins are in `remappedSrc`, it seems.

2021-08-04 21:51 UTC, YTG1234 commented on build.gradle.kts
>      }
This is now unnecessary as `release` is set.

2021-08-04 22:07 UTC, BeetMacol commented
Done, fixed those issues.

> On that note, I think I forgot to mention anywhere that this is an effectively read-only mirror, and only syncs GL->GH. I can (and probably will) merge this manually, but I would prefer that further PRs be opened on GitLab instead.

I thought it's a both way mirror. I can make a GL account and *merge request* there if it's a big trouble for you.

2021-08-05 06:16 UTC, merged

2021-08-05 06:16 UTC, YTG1234 commented
> I thought it's a both way mirror.

I would have made it so, but it's apparently unstable and unsupported.